-- Migration: Create master_table for Dash Super Report import
-- Run this in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS master_table (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  job_number TEXT,
  job_status TEXT,
  date_started DATE,
  customer TEXT,
  job_name TEXT,
  division TEXT,
  reason_for_closing TEXT,
  loss_category TEXT,
  supervisor TEXT,
  target_completion_date DATE,
  foreperson TEXT,
  coordinator TEXT,
  estimator TEXT,
  marketing_person TEXT,
  date_received TIMESTAMPTZ,
  claim_number TEXT,
  state TEXT,
  target_start_date TIMESTAMPTZ,
  date_inventoried DATE,
  customer_primary_contact_number TEXT,
  date_inspected DATE,
  estimate_sent_date DATE,
  city TEXT,
  date_of_majority_completion DATE,
  date_invoiced DATE,
  date_paid DATE,
  date_closed DATE,
  address TEXT,
  zip TEXT,
  total_estimates NUMERIC,
  total_invoiced NUMERIC,
  referred_by TEXT,
  referral_type TEXT,
  reported_by TEXT,
  total_job_cost NUMERIC,
  estimated_gp_pct NUMERIC,
  working_gross_profit_pct NUMERIC,
  actual_gross_profit_pct NUMERIC,
  total_collected NUMERIC,
  survey_score TEXT,
  external_file_number TEXT,
  last_journal_note_datetime TIMESTAMPTZ,
  last_journal_note_entered TEXT,
  company_contact_name TEXT,
  insured_contacted TIMESTAMPTZ,
  tags TEXT,
  estimate_owner TEXT,
  dispatcher TEXT,
  imported_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: allow authenticated users full access
ALTER TABLE master_table ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_all" ON master_table FOR ALL TO authenticated USING (true) WITH CHECK (true);
